services:
  postgres:
    image: postgres:14
    container_name: postgres-stock-ai
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservices_auth
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d prefect"]
      interval: 10s
      timeout: 10s
      retries: 5

  prefect-server:
    image: prefecthq/prefect:3-latest
    container_name: prefect-server
    ports:
      - "4200:4200"
    volumes:
      - ./data/prefect_data:/root/.prefect
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://admin:admin@postgres-stock-ai:5432/prefect
    command: prefect server start --host 0.0.0.0
    networks:
      - microservices_auth
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
    working_dir: /mlflow
    networks:
      - microservices_auth
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      timeout: 10s
      retries: 5

  stock-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-ai
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./mlruns:/app/mlruns
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - PREFECT_API_URL=http://prefect-server:4200/api
    networks:
      - microservices_auth
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      prefect-server:
        condition: service_started
      mlflow-server:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    container_name: stock-ai-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - microservices_auth
    depends_on:
      - stock-ai

  grafana:
    image: grafana/grafana
    container_name: stock-ai-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    networks:
      - microservices_auth
    depends_on:
      - prometheus

networks:
  microservices_auth:
    external: true
    name: microservices_auth
