global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'stock-ai'
    static_configs:
      - targets: ['stock-ai:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - localhost:9090