global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']

  - job_name: 'training-service'
    static_configs:
      - targets: ['training-service:8000']

  - job_name: 'data-processing-service'
    static_configs:
      - targets: ['data-processing-service:8000']

  - job_name: 'news-service'
    static_configs:
      - targets: ['news-service:8000']

  - job_name: 'deployment-service'
    static_configs:
      - targets: ['deployment-service:8000'] 

  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - localhost:9090