{
 "title": "Monolithe – Performance",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "4 Golden Signals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global Traffic",
   "type": "timeseries",
   "description": "This panel shows the total number of HTTP requests received by each endpoint over a given interval.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    http_requests_total{endpoint!~\"/health|/metrics|/docs|/openapi.json\"}[$__rate_interval]\r\n  )\r\n) by (endpoint)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(\r\n  increase(http_requests_total{endpoint!~\"/health|/metrics|/docs|/openapi.json\"}[$__rate_interval])\r\n  )",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "External Trafic",
   "type": "timeseries",
   "description": "This metric calculates the rate of external requests over time, aggregated by the site label. It provides insight into how many external requests are being made per second, broken down by site, over a specified time interval.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(site) (rate(external_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Represents the number of requests within a system for a given endpoint over a given time interval.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_errors_total[$__rate_interval])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence (ms)",
   "type": "timeseries",
   "description": "Measures the time it takes for a request to travel from the source to the destination and back, typically expressed in milliseconds (ms) for a specific endpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum(rate(http_request_duration_seconds_bucket{endpoint!~\"/health|/metrics|/docs|/openapi.json\"}[$__rate_interval])) by (le, endpoint)\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum(\r\n    rate(http_request_duration_seconds_bucket{endpoint!~\"/health|/metrics|/docs|/openapi.json\"}[$__rate_interval])\r\n  ) by (le)\r\n)",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "CPU Usage (Saturation)",
   "type": "bargauge",
   "description": "Indicates the percentage of total CPU capacity currently in use across all cores. This metric reflects how heavily the CPU is being utilized by a specific endpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(cpu_saturation_percentage)", "legendFormat": "Average" },
    {
     "expr": "avg(cpu_saturation_percentage{endpoint!~\"/metrics|/health|/docs|/openapi.json\"}) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (Saturation) (GB)",
   "type": "timeseries",
   "description": "Represents the amount of system memory currently in use, measured in gigabytes (GB). This metric indicates how much memory is actively consumed by a specific endpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "avg(memory_saturation_usage{endpoint!~\"/metrics|/health|/docs|/openapi.json\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "avg(memory_saturation_usage{endpoint!~\"/metrics|/health|/docs|/openapi.json\"}) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ML/AI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Price Prediction Confidence",
   "type": "gauge",
   "description": "Represents the probability or certainty that the model's prediction is correct, typically expressed as a percentage or score between 0 and 1. A higher confidence value indicates that the model is more certain about its prediction, while a lower value suggests greater uncertainty.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(prediction_confidence) by (model_type, symbol)",
     "legendFormat": "{{symbol}} | {{model_type}} "
    }
   ]
  },
  {
   "title": "Sentiment Analysis Time",
   "type": "timeseries",
   "description": "Time spent doing sentiment analysis in secs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(sentiment_analysis_time_seconds_sum[$__rate_interval]) \r\n/\r\nrate(sentiment_analysis_time_seconds_count[$__rate_interval])",
     "legendFormat": "Avg Sentiment Time"
    }
   ]
  }
 ]
}