{
 "title": "Monolithe – Performance",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Global Traffic",
   "type": "timeseries",
   "description": "This panel shows the total number of HTTP requests received by each endpoint over the past 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(\r\n  increase(\r\n    http_requests_total{endpoint!~\"/health|/metrics|/docs|/openapi.json\"}[5m]\r\n  )\r\n) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "latence (ms)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, handler))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(prediction_time_seconds_bucket[1m])) by (le, model_type, symbol))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (Saturation) (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "training_memory_mb_usage_percent",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(predictions_total{result=\"error\"}[1m])) by (model_type, symbol)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (Saturation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "training_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Traffic: Number of Predictions per Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(predictions_total[1m])) by (model_type, symbol)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Confidence",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "prediction_confidence", "legendFormat": "__auto" }
   ]
  }
 ]
}